import type { PortfolioContent } from '@/types/portfolio';

export const BUNDLED_PORTFOLIO: PortfolioContent = {
  about: [
    'Sahil Basumatary',
    '=================',
    "CS @ King's College London",
    '',
    "I set targets every day and work until they're done.",
    '',
    'Open source collaborator, community first. I lead from the',
    "front and I don't cut corners.",
    '',
    "I only prioritise work that keeps me awake — if it doesn't",
    "excite me, I won't build it.",
    '',
    'Poker. Tennis court. Saint-Tropez when I can.',
    '',
    "First one in, last one to leave. I don't really do breaks.",
    'But I connect with people fast — give me five minutes and',
    "we'll have a genuine conversation.",
  ].join('\n'),
  projects: [
    {
      slug: 'personal-blog',
      title: 'Personal Blog',
      summary: 'Personal journal — writing about learning, building, life.',
      readme: [
        '# Personal Blog',
        '',
        "My journal. I write about what I'm learning, things I'm building,",
        'and the occasional thought that refuses to leave my head.',
        '',
        '## Why it exists',
        '',
        'Writing forces clarity. If I can explain something to a reader',
        "who has zero context, I probably understand it. If I can't, I don't.",
        '',
        '## Stack notes',
        '',
        '- React on the front, Express on the back — boring on purpose.',
        '- Clerk handles auth so I never touch passwords.',
        '- PostgreSQL because Postgres is forever.',
        '',
        'See `tech-stack.json` for the full breakdown.',
      ].join('\n'),
      techStack: [
        'TypeScript',
        'JavaScript',
        'React',
        'Express',
        'Node.js',
        'PostgreSQL',
        'Clerk',
        'Vercel',
      ],
      liveUrl: 'https://blog.sahilbzy.com',
      githubUrl: null,
    },
    {
      slug: 'pioni',
      title: 'Pioni',
      summary:
        'Live trading intelligence — reads sentiment before markets move.',
      readme: [
        '# Pioni',
        '',
        'Live trading intelligence platform. Pioni reads human emotions and',
        'social sentiment to surface signals before the market reacts.',
        '',
        '## The bet',
        '',
        'Price action is downstream of attention. If you can read the room',
        "fast enough, you're not predicting the future — you're just",
        'listening more carefully than everyone else.',
        '',
        '## Stack notes',
        '',
        '- FastAPI for the ingestion + signals API.',
        '- PostgreSQL because time-series + relational both matter here.',
        '- Hosted on Render for now; will move when latency demands it.',
        '',
        'See `tech-stack.json` for the full breakdown.',
      ].join('\n'),
      techStack: ['Python', 'FastAPI', 'PostgreSQL', 'Render'],
      liveUrl: 'https://pioni.onrender.com',
      githubUrl: null,
    },
    {
      slug: 'tennisly',
      title: 'Tennisly',
      summary: 'Interactive tennis match visualization and analytics.',
      readme: [
        '# Tennisly',
        '',
        'Interactive tennis match visualization and data analytics.',
        'Live court rendering, point-by-point replays, player-vs-player',
        'analytics.',
        '',
        '## Status: WIP',
        '',
        'Backend is the priority right now — match state machine, ingest',
        'from match feeds, and a clean analytics layer. The court canvas',
        'comes after the data is honest.',
        '',
        '## Stack notes',
        '',
        '- Spring Boot for the core service.',
        '- React + canvas for the court.',
        '- PostgreSQL for matches, players, points.',
        '',
        'See `tech-stack.json` for the full breakdown.',
      ].join('\n'),
      techStack: ['Java', 'TypeScript', 'React', 'Spring Boot', 'PostgreSQL'],
      liveUrl: null,
      githubUrl: null,
    },
  ],
  skills: {
    languages: ['TypeScript', 'JavaScript', 'Python', 'Java', 'SQL'],
    frontend: ['React', 'Next.js', 'Tailwind CSS', 'HTML/CSS'],
    backend: ['Node.js', 'Express', 'FastAPI', 'Spring Boot'],
    tools: ['Git', 'Docker', 'PostgreSQL', 'MongoDB', 'Vercel'],
    interests: ['Distributed Systems', 'Machine Learning', 'Open Source'],
  },
};
