import type { PortfolioContent } from '@/types/portfolio';

export const BUNDLED_PORTFOLIO: PortfolioContent = {
  about: [
    'Sahil Basumatary',
    '=================',
    "CS @ King's College London",
    '',
    "I set targets every day and work until they're done.",
    '',
    'Open source collaborator, community first. I lead from the',
    "front and I don't cut corners.",
    '',
    "I only prioritise work that keeps me awake — if it doesn't",
    "excite me, I won't build it.",
    '',
    'Poker. Tennis court. Saint-Tropez when I can.',
    '',
    "First one in, last one to leave. I don't really do breaks.",
    'But I connect with people fast — give me five minutes and',
    "we'll have a genuine conversation.",
  ].join('\n'),
  projects: [
    {
      slug: 'personal-blog',
      title: 'Personal Blog',
      summary: 'Personal journal — writing about learning, building, life.',
      readme: [
        '# Personal Blog',
        '',
        "My journal. I write about what I'm learning, things I'm building,",
        'and the occasional thought that refuses to leave my head.',
        '',
        '## Why it exists',
        '',
        'Writing forces clarity. If I can explain something to a reader',
        "who has zero context, I probably understand it. If I can't, I don't.",
        '',
        '## Stack notes',
        '',
        '- React + Vite SPA, Express API, MongoDB via Mongoose.',
        '- Clerk for owner-only auth; Jest + mongodb-memory-server for tests.',
        '- GitHub Actions CI on every push.',
        '',
        'See `tech-stack.json` for the full breakdown.',
      ].join('\n'),
      techStack: [
        'JavaScript',
        'TypeScript',
        'React',
        'Vite',
        'React Router',
        'Node.js',
        'Express',
        'MongoDB',
        'Mongoose',
        'Clerk',
        'Jest',
        'GitHub Actions',
      ],
      liveUrl: 'https://blog.sahilbzy.com',
      githubUrl: null,
      images: [],
    },
    {
      slug: 'pioni',
      title: 'Pioni',
      summary:
        'Live paper-trading platform — crypto orders with live market data and sentiment.',
      readme: [
        '# Pioni',
        '',
        'Live paper-trading platform for practising crypto orders with live',
        'market data and simulated USD. Spot and margin orders, portfolio',
        'risk, and market sentiment from news and social sources.',
        '',
        '## The bet',
        '',
        'Price action is downstream of attention. If you can read the room',
        "fast enough, you're not predicting the future — you're just",
        'listening more carefully than everyone else.',
        '',
        '## Stack notes',
        '',
        '- React 19 + TypeScript frontend (Vite, Redux Toolkit, Tailwind).',
        '- FastAPI microservices behind a gateway (orders, portfolio, market data, sentiment).',
        '- PostgreSQL + Redis + RabbitMQ; Clerk auth; observability with Prometheus/Grafana/Jaeger.',
        '',
        'See `tech-stack.json` for the full breakdown.',
      ].join('\n'),
      techStack: [
        'TypeScript',
        'React',
        'Vite',
        'Redux Toolkit',
        'Tailwind CSS',
        'Python',
        'FastAPI',
        'PostgreSQL',
        'Redis',
        'RabbitMQ',
        'Clerk',
        'Docker',
        'Render',
      ],
      liveUrl: 'https://www.pioni.ai',
      githubUrl: null,
      images: [],
    },
    {
      slug: 'tennisly',
      title: 'Tennisly',
      summary: 'Interactive tennis match visualization and analytics.',
      readme: [
        '# Tennisly',
        '',
        'Interactive tennis match visualization and data analytics.',
        'Live court rendering, point-by-point replays, player-vs-player',
        'analytics — live at tennisly.tv.',
        '',
        '## Status: Live',
        '',
        'Match ingest from real tennis feeds, synthesized ball trajectories',
        'from the point ledger, and analytics indexed for the public web app.',
        '',
        '## Stack notes',
        '',
        '- Spring Boot / Spring Cloud microservices (Java 21).',
        '- Next.js + React web app with Babylon.js court visualization.',
        '- PostgreSQL, Redis, Elasticsearch; Clerk auth; Vercel + Render.',
        '',
        'See `tech-stack.json` for the full breakdown.',
      ].join('\n'),
      techStack: [
        'Java',
        'Spring Boot',
        'Spring Cloud',
        'TypeScript',
        'Next.js',
        'React',
        'Babylon.js',
        'PostgreSQL',
        'Redis',
        'Elasticsearch',
        'Clerk',
        'Docker',
        'Vercel',
        'Render',
      ],
      liveUrl: 'https://tennisly.tv',
      githubUrl: null,
      images: [],
    },
  ],
  skills: {
    languages: [
      { name: 'TypeScript', proficiency: 'advanced' },
      { name: 'JavaScript', proficiency: 'advanced' },
      { name: 'Python', proficiency: 'intermediate' },
      { name: 'Java', proficiency: 'intermediate' },
      { name: 'SQL', proficiency: 'intermediate' },
    ],
    frontend: ['React', 'Next.js', 'Tailwind CSS', 'HTML/CSS'],
    backend: ['Node.js', 'Express', 'FastAPI', 'Spring Boot'],
    tools: ['Git', 'Docker', 'PostgreSQL', 'MongoDB', 'Vercel'],
    interests: ['Distributed Systems', 'Machine Learning', 'Open Source'],
  },
};
