export type Language = 'javascript' | 'typescript' | 'python';

export const DEFAULT_CODE: Record<Language, string> = {
  javascript: [
    '// JavaScript Playground',
    'console.log("Hello, World!");',
    '',
  ].join('\n'),
  typescript: [
    '// TypeScript Playground',
    'const greeting: string = "Hello, World!";',
    'console.log(greeting);',
    '',
  ].join('\n'),
  python: ['# Python Playground', 'print("Hello, World!")', ''].join('\n'),
};

export const SNIPPETS: Record<Language, { label: string; code: string }[]> = {
  javascript: [
    {
      label: 'Array Methods',
      code: [
        'const numbers = [1, 2, 3, 4, 5];',
        '',
        'const doubled = numbers.map(n => n * 2);',
        'console.log("Doubled:", doubled);',
        '',
        'const evens = numbers.filter(n => n % 2 === 0);',
        'console.log("Evens:", evens);',
        '',
        'const sum = numbers.reduce((acc, n) => acc + n, 0);',
        'console.log("Sum:", sum);',
      ].join('\n'),
    },
    {
      label: 'Fibonacci',
      code: [
        'function fibonacci(n) {',
        '  if (n <= 1) return n;',
        '  return fibonacci(n - 1) + fibonacci(n - 2);',
        '}',
        '',
        'for (let i = 0; i < 10; i++) {',
        '  console.log(`fib(${i}) = ${fibonacci(i)}`);',
        '}',
      ].join('\n'),
    },
    {
      label: 'Closures',
      code: [
        'function createCounter(initial = 0) {',
        '  let count = initial;',
        '  return {',
        '    increment: () => ++count,',
        '    decrement: () => --count,',
        '    value: () => count,',
        '  };',
        '}',
        '',
        'const counter = createCounter();',
        'console.log(counter.increment());',
        'console.log(counter.increment());',
        'console.log(counter.increment());',
        'console.log(counter.decrement());',
        'console.log("Final:", counter.value());',
      ].join('\n'),
    },
    {
      label: 'Async/Await',
      code: [
        'function delay(ms) {',
        '  return new Promise(resolve => setTimeout(resolve, ms));',
        '}',
        '',
        'async function main() {',
        '  console.log("Starting...");',
        '  await delay(500);',
        '  console.log("500ms elapsed");',
        '  await delay(500);',
        '  console.log("1s elapsed");',
        '  console.log("Done!");',
        '}',
        '',
        'main();',
      ].join('\n'),
    },
  ],
  typescript: [
    {
      label: 'Generics',
      code: [
        'function identity<T>(value: T): T {',
        '  return value;',
        '}',
        '',
        'console.log(identity<string>("hello"));',
        'console.log(identity<number>(42));',
        '',
        'function firstElement<T>(arr: T[]): T | undefined {',
        '  return arr[0];',
        '}',
        '',
        'console.log(firstElement([10, 20, 30]));',
        'console.log(firstElement(["a", "b", "c"]));',
      ].join('\n'),
    },
    {
      label: 'Interfaces & Classes',
      code: [
        'interface Printable {',
        '  toString(): string;',
        '}',
        '',
        'class User implements Printable {',
        '  constructor(',
        '    public name: string,',
        '    public email: string,',
        '    private age: number',
        '  ) {}',
        '',
        '  toString(): string {',
        '    return `${this.name} <${this.email}> (${this.age})`;',
        '  }',
        '}',
        '',
        'const user = new User("Sahil", "sahil@example.com", 19);',
        'console.log(user.toString());',
      ].join('\n'),
    },
    {
      label: 'Enums & Union Types',
      code: [
        'enum Status {',
        '  Active = "ACTIVE",',
        '  Inactive = "INACTIVE",',
        '  Pending = "PENDING",',
        '}',
        '',
        'type Result<T> =',
        '  | { ok: true; value: T }',
        '  | { ok: false; error: string };',
        '',
        'function getStatus(s: Status): Result<string> {',
        '  if (s === Status.Active) {',
        '    return { ok: true, value: "User is active" };',
        '  }',
        '  return { ok: false, error: "User not active" };',
        '}',
        '',
        'const result = getStatus(Status.Active);',
        'console.log(result);',
      ].join('\n'),
    },
  ],
  python: [
    {
      label: 'List Comprehensions',
      code: [
        'numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]',
        '',
        'squares = [n ** 2 for n in numbers]',
        'print("Squares:", squares)',
        '',
        'evens = [n for n in numbers if n % 2 == 0]',
        'print("Evens:", evens)',
        '',
        'matrix = [[i * j for j in range(1, 4)] for i in range(1, 4)]',
        'for row in matrix:',
        '    print(row)',
      ].join('\n'),
    },
    {
      label: 'Classes & Inheritance',
      code: [
        'class Animal:',
        '    def __init__(self, name: str, sound: str):',
        '        self.name = name',
        '        self.sound = sound',
        '',
        '    def speak(self) -> str:',
        '        return f"{self.name} says {self.sound}!"',
        '',
        'class Dog(Animal):',
        '    def __init__(self, name: str):',
        '        super().__init__(name, "Woof")',
        '',
        '    def fetch(self, item: str) -> str:',
        '        return f"{self.name} fetches the {item}!"',
        '',
        'dog = Dog("Rex")',
        'print(dog.speak())',
        'print(dog.fetch("ball"))',
      ].join('\n'),
    },
    {
      label: 'Fibonacci Generator',
      code: [
        'def fibonacci(limit):',
        '    a, b = 0, 1',
        '    while a < limit:',
        '        yield a',
        '        a, b = b, a + b',
        '',
        'for num in fibonacci(100):',
        '    print(num, end=" ")',
        'print()',
      ].join('\n'),
    },
    {
      label: 'Dictionary Operations',
      code: [
        'students = {',
        '    "Alice": {"grade": "A", "score": 95},',
        '    "Bob": {"grade": "B", "score": 85},',
        '    "Charlie": {"grade": "A", "score": 92},',
        '    "Diana": {"grade": "C", "score": 78},',
        '}',
        '',
        'a_students = {',
        '    name: info for name, info in students.items()',
        '    if info["grade"] == "A"',
        '}',
        'print("A students:", a_students)',
        '',
        'avg = sum(s["score"] for s in students.values()) / len(students)',
        'print(f"Average score: {avg:.1f}")',
      ].join('\n'),
    },
  ],
};
